# ===== PERFIL PROD - PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/worldcupdb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.h2.console.enabled=false

spring.flyway.enabled=true

# ===== Logging (prod: mais enxuto) =====
# Em producao, nosso pacote em INFO (sem DEBUG ruidoso).
logging.level.root=WARN
logging.level.com.portfolio.worldcup=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%logger{36}] - %msg%n
# (JSON de log para producao fica preparado para ligar na Fase E - deploy.)