-- ============================================================
-- V1 - Esquema inicial da World Cup API
-- SQL portavel (compativel com H2 e PostgreSQL).
-- Os enums (status, type) sao gravados como VARCHAR;
-- a validacao dos valores e feita no lado Java (@Enumerated(EnumType.STRING)).
-- ============================================================

-- ---------- TEAMS ----------
CREATE TABLE teams (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id BIGINT,
    name        VARCHAR(255) NOT NULL,
    code        VARCHAR(3),
    team_group  VARCHAR(255),
    flag_url    VARCHAR(255),
    logo_url    VARCHAR(255),
    CONSTRAINT uk_teams_external_id UNIQUE (external_id)
);

-- ---------- PLAYERS ----------
CREATE TABLE players (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    position     VARCHAR(255),
    shirt_number INTEGER,
    team_id      BIGINT,
    CONSTRAINT fk_players_team FOREIGN KEY (team_id) REFERENCES teams (id)
);

-- ---------- MATCHES ----------
CREATE TABLE matches (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id     BIGINT,
    home_team_id    BIGINT,
    away_team_id    BIGINT,
    home_score      INTEGER NOT NULL DEFAULT 0,
    away_score      INTEGER NOT NULL DEFAULT 0,
    match_date_time TIMESTAMP,
    stadium         VARCHAR(255),
    city            VARCHAR(255),
    league          VARCHAR(255),
    round           VARCHAR(255),
    status          VARCHAR(50) NOT NULL,
    current_minute  INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_matches_external_id UNIQUE (external_id),
    CONSTRAINT fk_matches_home_team FOREIGN KEY (home_team_id) REFERENCES teams (id),
    CONSTRAINT fk_matches_away_team FOREIGN KEY (away_team_id) REFERENCES teams (id)
);

-- ---------- MATCH_EVENTS ----------
CREATE TABLE match_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id      BIGINT,
    player_id     BIGINT,
    team_id       BIGINT,
    type          VARCHAR(50) NOT NULL,
    event_minute  INTEGER NOT NULL,
    description   VARCHAR(255),
    CONSTRAINT fk_events_match  FOREIGN KEY (match_id)  REFERENCES matches (id),
    CONSTRAINT fk_events_player FOREIGN KEY (player_id) REFERENCES players (id),
    CONSTRAINT fk_events_team   FOREIGN KEY (team_id)   REFERENCES teams (id)
);